"""Partition the vote journal by question_id.

Revision ID: 002_partition_vote
Revises: 001_init
"""

from collections.abc import Sequence

from alembic import op

revision: str = "002_partition_vote"
down_revision: str | Sequence[str] | None = "001_init"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

PARTITION_COUNT = 16


def upgrade() -> None:
    op.execute("ALTER TABLE vote RENAME TO vote_unpartitioned")
    op.execute(
        "ALTER TABLE vote_unpartitioned "
        "RENAME CONSTRAINT vote_pkey TO vote_unpartitioned_pkey"
    )
    op.execute(
        "ALTER TABLE vote_unpartitioned "
        "RENAME CONSTRAINT uq_vote_question_dedup TO uq_vote_unpartitioned_question_dedup"
    )
    op.execute(
        "ALTER INDEX ix_vote_question_option RENAME TO ix_vote_unpartitioned_question_option"
    )
    op.execute(
        """
        CREATE TABLE vote (
            question_id BIGINT NOT NULL
                REFERENCES question(id) ON DELETE RESTRICT,
            id BIGINT GENERATED BY DEFAULT AS IDENTITY,
            option_key VARCHAR(64) NOT NULL,
            dedup_key VARCHAR(64) NOT NULL,
            ip_hash VARCHAR(64) NOT NULL,
            voted_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT vote_pkey PRIMARY KEY (question_id, id),
            CONSTRAINT uq_vote_question_dedup UNIQUE (question_id, dedup_key)
        ) PARTITION BY HASH (question_id)
        """
    )
    for remainder in range(PARTITION_COUNT):
        op.execute(
            f"""
            CREATE TABLE vote_p{remainder:02d} PARTITION OF vote
            FOR VALUES WITH (MODULUS {PARTITION_COUNT}, REMAINDER {remainder})
            """
        )
    op.execute("CREATE INDEX ix_vote_question_option ON vote (question_id, option_key)")
    op.execute(
        """
        INSERT INTO vote (id, question_id, option_key, dedup_key, ip_hash, voted_at)
        SELECT id, question_id, option_key, dedup_key, ip_hash, voted_at
        FROM vote_unpartitioned
        """
    )
    op.execute(
        """
        SELECT setval(
            pg_get_serial_sequence('vote', 'id'),
            COALESCE((SELECT max(id) FROM vote), 1),
            EXISTS (SELECT 1 FROM vote)
        )
        """
    )
    op.drop_table("vote_unpartitioned")


def downgrade() -> None:
    op.execute("ALTER TABLE vote RENAME TO vote_partitioned")
    op.execute(
        "ALTER TABLE vote_partitioned "
        "RENAME CONSTRAINT vote_pkey TO vote_partitioned_pkey"
    )
    op.execute(
        "ALTER TABLE vote_partitioned "
        "RENAME CONSTRAINT uq_vote_question_dedup TO uq_vote_partitioned_question_dedup"
    )
    op.execute(
        "ALTER INDEX ix_vote_question_option RENAME TO ix_vote_partitioned_question_option"
    )
    op.execute(
        """
        CREATE TABLE vote (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            question_id BIGINT NOT NULL
                REFERENCES question(id) ON DELETE RESTRICT,
            option_key VARCHAR(64) NOT NULL,
            dedup_key VARCHAR(64) NOT NULL,
            ip_hash VARCHAR(64) NOT NULL,
            voted_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT uq_vote_question_dedup UNIQUE (question_id, dedup_key)
        )
        """
    )
    op.execute("CREATE INDEX ix_vote_question_option ON vote (question_id, option_key)")
    op.execute(
        """
        INSERT INTO vote (id, question_id, option_key, dedup_key, ip_hash, voted_at)
        SELECT id, question_id, option_key, dedup_key, ip_hash, voted_at
        FROM vote_partitioned
        """
    )
    op.execute(
        """
        SELECT setval(
            pg_get_serial_sequence('vote', 'id'),
            COALESCE((SELECT max(id) FROM vote), 1),
            EXISTS (SELECT 1 FROM vote)
        )
        """
    )
    op.drop_table("vote_partitioned")
